### ISSUE TITLE
shinycannon doesn't quit after all sessions completed

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinycannon#2]
With session = 10 or whatever, after all the sessions hit Done state, shinycannon still doesn't return to the prompt. I have to hit Ctrl+C or stop the server.

**Comment by alandipert** [comment]
This turned out to be caused by a [bug in the WebSocket library we use](https://github.com/TakahikoKawasaki/nv-websocket-client/issues/140). The workaround was to call `System.exit` after all workers have completed, which kills the outstanding TimerThreads and shuts down the JVM.
