### ISSUE TITLE
Java 11 reflection warning

### ISSUE THREAD

**Issue by alandipert** [rstudio/shinycannon#43]
On Linux, with OpenJDK 11, I see the following output when running shinycannon via `java -jar target/shinycannon-1.0.0-jar-with-dependencies.jar ...`:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$Ref
lectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoade
r.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.
internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
```

This is apparently a consequence of https://github.com/google/guice/issues/1133 and appears with versions of Java 9 and above.

It looks like we might be able to [add a `java` argument](https://github.com/google/guice/issues/1133#issuecomment-434635902) to our launcher scripts if the version of Java is 9+, but that would require sniffing the Java version.

`MAVEN_OPTS='--add-opens java.base/java.lang=ALL-UNNAMED' mvn test` makes the warnings go away when running tests.

**Comment by schloerke** [comment]
Fixed in https://github.com/rstudio/shinycannon/pull/65
