### ISSUE TITLE
Auth doesn't work with Oauth2.0 using shiny server pro on an aws instance

### ISSUE THREAD

**Issue by debshila** [rstudio/shinycannon#44]
Hello!
I ran shinyloadtest::record_session on a flexdashboard application with oauth2.0 authentication. The app was hosted using shiny server pro on an aws instance.While the session seemed to be recorded successfully with predefined `SHINYCANNON_USER` and `SHINYCANNON_PASS` values, I encountered the following error while running shinycannon:
```
2019-08-14 14:20:37.324 ERROR [thread01] - Playback failed: Status 404 received, expected 200, URL: https://REDACTED/_w_alphanumeric_sequence/fileXXXXXX_files/style.css, Response body: <h1>Not Found</h1>
java.lang.IllegalStateException: Status 404 received, expected 200, URL: https://REDACTED/_w_alphanumeric_sequence/fileXXXXXX_files/style.css, Response body: <h1>Not Found</h1>
	at com.rstudio.shinycannon.Event$Http.get(Events.kt:148)2019-08-14 14:20:37.325 INFO [thread01] - Running again
2019-08-14 14:20:37.479 INFO [thread01] - SHINYCANNON_USER and SHINYCANNON_PASS set, but target app doesn't require authentication.
```
It appears that the path to the style.css file was extracted from the record session, but since that path changes with every session, shinycannon is unable to locate it. All the tests fail by the end of the run.

**Comment by alandipert** [comment]
Hi, thank you for the report. I can see why OAuth wouldn't work currently and I apologize for not documenting that limitation. We'll look into it.

In the meantime, you might consider working around the issue by temporarily switching to PAM or basic auth just during your recording and playback activity. The authentication scheme shouldn't have an impact on your app's performance profile.

**Comment by debshila** [comment]
Thank you very much. I will look into trying the load test with basic auth. Would that resolve the file not being found issue?

**Comment by alandipert** [comment]
I'm guessing it will, but if it doesn't, it's a bug I'll be happy to investigate.

**Comment by schloerke** [comment]
While OAuth2.0 is not directly fixed, an SHINYCANNON_CONNECT_API_KEY can be supplied. 

Closing. Fixed in Enable RStudio Connect API Key and allow for headers #56
