### ISSUE TITLE
Auth using RStudio Connect API key 

### ISSUE THREAD

**Issue by jlfsjunior** [rstudio/shinycannon#48]
I was wondering if it is (or could be) possible to authenticate using the RStudio Connect API key instead of the password or other auth method described in the documentation.

If not, what would be the best way to keep my credentials safe (I don't like exporting passwords).

**Comment by alandipert** [comment]
Thanks for dropping by. I discussed this a few days ago with @colearendt at rstudio::conf and he brought this to my attention. We arrived at the idea of supporting the assignment of arbitrary HTTP headers to requests, in the manner of curl's `-H` parameter.

I think this would support the Connect API key, and possibly other more esoteric authentication cases that rely on custom headers. While this would be a relatively small amount of work to add, I don't know of any workarounds you could do until we have this feature.

I think it's something we can work on soon, though. Keep an eye on this issue for updates.

**Comment by colearendt** [comment]
For completeness - going to tie this to the community thread that generated the discussion 😄 

https://community.rstudio.com/t/how-to-run-shinycannon-using-an-rstudio-connect-api-key-instead-of-a-password/50476/3

**Comment by jlfsjunior** [comment]
Fantastic! Thanks @alandipert and @colearendt!
